
-
  name: 'Rest route for Api:readAll'
  uriPattern: webservice/api
  httpMethods:
    - GET
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Rest
    '@action': handle
    webservice: Api
    operation: readAll
    class: PerfectIn\Webservice\Api
    method: getForAllWebservices
-
  name: 'Soap route for Api'
  uriPattern: webservice/soap/security/role
  httpMethods:
    - POST
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Soap
    '@action': handle
    class: TYPO3\Flow\Security\Policy\RoleRepository
    webservice: Api
-
  name: 'Rest route for Api:read'
  uriPattern: 'webservice/security/role/{identifier}'
  httpMethods:
    - GET
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Rest
    '@action': handle
    webservice: Api
    operation: read
    class: TYPO3\Flow\Security\Policy\RoleRepository
    method: findByIdentifier
-
  name: 'Rest route for Presentation:readAll'
  uriPattern: webservice/ui/presentation
  httpMethods:
    - GET
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Rest
    '@action': handle
    webservice: Presentation
    operation: readAll
    class: PerfectIn\Ui\Service\PresentationService
    method: getYamlConfigurations
-
  name: 'Rest route for Presentation:read'
  uriPattern: 'webservice/ui/presentation/{identifier}'
  httpMethods:
    - GET
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Rest
    '@action': handle
    webservice: Presentation
    operation: read
    class: PerfectIn\Ui\Service\PresentationService
    method: getYamlConfiguration
-
  name: 'Rest route for Presentation:create'
  uriPattern: webservice/ui/presentation
  httpMethods:
    - POST
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Rest
    '@action': handle
    webservice: Presentation
    operation: create
    class: PerfectIn\Ui\Service\PresentationService
    method: createPresentation
-
  name: 'Rest route for Presentation:update'
  uriPattern: webservice/ui/presentation
  httpMethods:
    - PUT
  defaults:
    '@package': PerfectIn.Webservice
    '@controller': Rest
    '@action': handle
    webservice: Presentation
    operation: update
    class: PerfectIn\Ui\Service\PresentationService
    method: updatePresentation
