PerfectIn:
  Webservice:
    log:
      logger: TYPO3\Flow\Log\Logger
      backend: TYPO3\Flow\Log\Backend\FileBackend
      backendOptions:
         logFileURL: %FLOW_PATH_DATA%Logs/Webservice.log
         createParentDirectories: TRUE
         severityThreshold: %LOG_INFO%
         maximumLogFileSize: 10485760
         logFilesToKeep: 1
         logMessageOrigin: FALSE
